## Задание. 
Построить и обучить нейронную сеть для распознавания цифровых рукописных символов из базы данных MNIST (Mixed National Institute of Standards and Technology database). Нейронная сеть должна корректно распознавать образы из тестовой выборки в большинстве случаев

Импортируем необходимые библиотеки и MNIST.

In [2]:
import numpy as np
from PIL import Image

import matplotlib.pyplot as plt
import time

from statistics import mean

from tensorflow.keras.datasets import mnist

Делим данные на тренировочные и тестовые.

In [3]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [4]:
x_train = (x_train[0:2000].reshape(2000,28*28)) / 255
y_train = y_train[0:2000]

In [5]:
x_test = x_test[0:200].reshape(200,28*28) / 255

In [6]:
y_train[0]

5

Функция для задания класса каждой цифре.

In [7]:
def norm_train_y(y_data):
    train_y_all = []
    
    for i in y_data:
        y_arr = np.zeros(10)
        y_arr[i] = 1
        train_y_all.append(y_arr)
    return np.asarray(train_y_all)
        

In [8]:
train_y = norm_train_y(y_train)

В качестве функции активации будем использовать  сигмоиду.

In [9]:
#activation function
def act_func(x):
    return 1/(1+np.exp(-x))

Производная функции активации.

In [10]:
#activation function derivative
def act_func_deriv(x):
    fx = act_func(x)
    if (fx*(1 - fx))==0:
        return 0
    return fx*(1 - fx)

Генерируем веса.

In [93]:
w = np.zeros((10,784))
for i in range(10):
    for j in range(784):
        w[i][j] = np.random.rand()

print(w)


[[0.90629933 0.23130808 0.57885754 ... 0.35104251 0.99106001 0.14008217]
 [0.00882149 0.47423738 0.5023463  ... 0.39182991 0.24481897 0.23562829]
 [0.51814679 0.45010295 0.43161761 ... 0.95652397 0.05405175 0.25225954]
 ...
 [0.67756066 0.58223364 0.8682706  ... 0.04173832 0.57211843 0.0489018 ]
 [0.25986373 0.07361003 0.53246071 ... 0.052451   0.31387527 0.75556149]
 [0.00893122 0.77915703 0.18962986 ... 0.33622853 0.24014851 0.89121028]]


Функция для более понятного вывода. Классу, у которого наибольшая вероятность, ставит единицу, остальным - 0.

In [95]:
def beautiful_out(x):
    max_value = max(x)
    max_indx = np.where(x==max_value)[0]
    return max_indx

Функция для подсчета среднеквадратичной ошибки.

In [96]:
def error_calc(calc_out, correct_result):               
    return (correct_result - calc_out)**2

Функция для подсчета точности.

In [97]:
def accuracy(true_prediction, correct):
    return true_prediction/correct

Функция обучния нейронной сети.

In [98]:
def train(train_image, correct_result):
    global w
    
    alpha = 0.001
    prediction = np.zeros(10)
    
    e_all = 0
    
    for epoch in range(10):
        error_all = 0
        k = 0
        for i in range(len(train_image)):
            error = 0
            
            for j in range(10):
                
                
                
                prediction[j] = act_func(np.dot(train_image[i][:],w[j][:]))

                w_delta =  -2*(prediction[j]-correct_result[i][j])-alpha*(act_func_deriv(prediction[j]-correct_result[i][j])) 


                for n in range(784):
                    w[j][n] = w[j][n] + w_delta*train_image[i][n]


                error += np.sum(error_calc(prediction[j], correct_result[i][j]))
            error_all += error
           
            if np.array_equal(beautiful_out(prediction),beautiful_out(correct_result[i])):
                k+=1

        accur = accuracy(k, len(correct_result))
            
        print("Epoch " + str(epoch)  + ":\tError:" + str(error_all/len(train_image)) + " \tAccuracy:" + str(accur)) 

          
    return w

In [99]:
train(x_train, train_y)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19220\3198915338.py:3: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))


Epoch 0:	Error:0.8571960962032596 	Accuracy:0.556
Epoch 1:	Error:0.5578793656510698 	Accuracy:0.7065
Epoch 2:	Error:0.45789445704121146 	Accuracy:0.7815
Epoch 3:	Error:0.3690012766023088 	Accuracy:0.8105
Epoch 4:	Error:0.34600808315719156 	Accuracy:0.8325
Epoch 5:	Error:0.2868144617580744 	Accuracy:0.857
Epoch 6:	Error:0.2711112707174385 	Accuracy:0.876
Epoch 7:	Error:0.2687843113512065 	Accuracy:0.876
Epoch 8:	Error:0.23573434869803506 	Accuracy:0.903
Epoch 9:	Error:0.22326249266051876 	Accuracy:0.896


array([[0.90629933, 0.23130808, 0.57885754, ..., 0.35104251, 0.99106001,
        0.14008217],
       [0.00882149, 0.47423738, 0.5023463 , ..., 0.39182991, 0.24481897,
        0.23562829],
       [0.51814679, 0.45010295, 0.43161761, ..., 0.95652397, 0.05405175,
        0.25225954],
       ...,
       [0.67756066, 0.58223364, 0.8682706 , ..., 0.04173832, 0.57211843,
        0.0489018 ],
       [0.25986373, 0.07361003, 0.53246071, ..., 0.052451  , 0.31387527,
        0.75556149],
       [0.00893122, 0.77915703, 0.18962986, ..., 0.33622853, 0.24014851,
        0.89121028]])

Вывод весов.

In [100]:
print(w)

[[0.90629933 0.23130808 0.57885754 ... 0.35104251 0.99106001 0.14008217]
 [0.00882149 0.47423738 0.5023463  ... 0.39182991 0.24481897 0.23562829]
 [0.51814679 0.45010295 0.43161761 ... 0.95652397 0.05405175 0.25225954]
 ...
 [0.67756066 0.58223364 0.8682706  ... 0.04173832 0.57211843 0.0489018 ]
 [0.25986373 0.07361003 0.53246071 ... 0.052451   0.31387527 0.75556149]
 [0.00893122 0.77915703 0.18962986 ... 0.33622853 0.24014851 0.89121028]]


Для тестовой выборки возьмем 10% от тренировочной выборки.

In [101]:
test_y = y_test[0:200]
test_y = norm_train_y(test_y)

In [102]:
test_y

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

Функция классификации для тестовых данных.

In [103]:
def result(img, correct):    
    prediction = np.zeros(10)
    
    error_all = 0
    k = 0
    for i in range(len(img)):
        error = 0
       
        for j in range(10):
                
            prediction[j] = act_func(np.dot(img[i][:],w[j][:]))
            error += np.sum(error_calc(prediction[j], correct[i][j]))
        error_all += error
        
        if np.array_equal(beautiful_out(prediction),beautiful_out(correct[i])):
            k+=1

    accur = accuracy(k, len(correct))
    print("Error: " + str(error_all/len(img))+"\tAccuracy: "+str(accur))

   

In [104]:
y_test[36]

7

Вывод ошибки и точности при тестировании.

In [108]:
result(x_test, test_y)

Error: 0.36386120015995205	Accuracy: 0.825


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_19220\3198915338.py:3: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-x))
